
// Les communes de l'archipel de la Société

INSERT INTO ARCHIPEL (NAME) VALUES ('société');

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tahiti', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('afaahiti (taiarapu est)', '98719', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('arue', '98701', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('faaa (B.P. & P.R.)', '98702', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('faaa (domicile)', '98704', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('faaone (taiarapu est)', '98720', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hitiaa o te ra', '98705', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('mahaena (hitiaa o te ra)', '98706', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('mahina', '98709', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('mataiea (teva i uta)', '98726', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('paea', '98711', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('papara', '98712', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('papeari (teva i uta)', '98727', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('papeete (B.P. & P.R.)', '98713', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('papeete (domicile)', '98714', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('papeete-C.T.C. (B.P. & P.R.)', '98715', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('papenoo (hitiaa o te ra)', '98707', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('pirae', '98716', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('punaauia (B.P.13000 & 130000)', '98717', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('punaauia (B.P.380000 ss)', '98718', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('punaauia centre', '98703', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('pueu (taiarapu est)', '98721', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('taravao (lieu-dit)', '98719', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tautira (taiarapu est)', '98722', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('teahupoo (taiarapu ouest)', '98723', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tiarei (hitiaa o te ra)', '98708', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('toahotu (taiarapu ouest)', '98724', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('vairao (taiarapu ouest)', '98725', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('village d orofara', '98710', 1);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('moorea', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('moorea-maiao/afareaitu', '98728', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('moorea-maiao/haapiti', '98729', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('moorea-maiao/maiao', '98704Céd99', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('moorea-maiao/paopao', '98728', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('moorea-maiao/papetoai', '98729', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('moorea-maiao/teavarao', '98728', 2);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('bora-bora', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('bora-bora/anau', '98730', 3);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('bora-bora/faanui', '98730', 3);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('bora-bora/nuenue', '98730', 3);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('huahine', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('huahine/faie', '98731', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('huahine/fare', '98731', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('huahine/fitii', '98731', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('huahine/haapu', '98731', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('huahine/maeva', '98731', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('huahine/maroe', '98731', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('huahine/parea', '98731', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('huahine/tefarerii', '98731', 4);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('maupiti', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('maupiti', '98732', 5);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tahaa', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tahaa/faaaha', '98734', 6);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tahaa/haamene', '98734', 6);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tahaa/hipu', '98733', 6);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tahaa/iripau', '98733', 6);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tahaa/niua', '98734', 6);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tahaa/ruutia', '98733', 6);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tahaa/tapuamu', '98733', 6);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tahaa/vaitoare', '98734', 6);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('raiatea', 1);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('taputapuatea', '98735', 7);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('taputapuatea/avera', '98736', 7);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('taputapuatea/opoa', '98735', 7);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('taputapuatea/puohine', '98735', 7);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tumaraa', '98735', 7);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tumaraaa/fetuna', '98735', 7);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tumaraaa/tehurui', '98735', 7);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tumaraaa/tevaitoa', '98735', 7);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tumaraaa/vaiaau', '98735', 7);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('uturoa', '98735', 7);


INSERT INTO ARCHIPEL (NAME) VALUES ('marquises');

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('fatu-hiva', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('fatuhiva/omoa', '98740', 8);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('mohotani', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hiva-oa', '98796', 9);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('fatu huku', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hiva-oa', '98796', 10);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('hiva-oa', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hiva-oa/atuona', '98741', 11);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hiva-oa/puamau', '98749', 11);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('eiao', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('nuku-hiva', '98796', 12);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('hatu iti', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('nuku-hiva', '98796', 13);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('hatutaa', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('nuku-hiva', '98796', 14);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('nuku-hiva', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('nuku-hiva/hatiheu', '98748', 15);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('nuku-hiva/taipivai', '98742', 15);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tahuata', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tahuata/vaitahu', '98743', 16);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('ua-huka', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('ua-huka/hanavave', '98744', 17);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('ua-huka/hane', '98747', 17);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('ua-pou', 2);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('ua-pou/hakahau', '98745', 18);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('ua-pou/hakamai', '98746', 18);


INSERT INTO ARCHIPEL (NAME) VALUES ('australes');

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('raivavae', 3);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('raivavae/anatonu', '98750', 19);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('raivavae/rairua', '98750', 19);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('raivavae/vaiuru', '98750', 19);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('marotiri', 3);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('rapa', '98794', 20);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('rapa', 3);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('rapa/ahurei', '98751', 21);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('rimatara', 3);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('rimatara/amaru', '98752', 22);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('rimatara/anapoto', '98752', 22);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('rimatara/utuaura', '98752', 22);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('rurutu/mutuaura', '98752', 22);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('rurutu', 3);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('rurutu/avera', '98753', 23);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('rurutu/hauti', '98753', 23);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('rurutu/moerai', '98753', 23);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tubuai', 3);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tubuai/mahu', '98754', 24);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tubuai/mataura', '98754', 24);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tubuai/taahuaia', '98754', 24);





INSERT INTO ARCHIPEL (NAME) VALUES ('tuamotu-gambier');

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('anaa', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('anaa', '98760', 25);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('faaite', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('anaa/faaite', '98786', 26);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('motutunga', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('anaa/faaite', '98786', 27);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tahanea', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('anaa/faaite', '98786', 28);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('apataki', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('apataki/niutahi', '98762', 29);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('arutua', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('arutua', '98761', 30);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('kaukura', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('arutua/kaukura', '98785', 31);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('fakarava', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('fakarava', '98763', 32);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('raraka', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('fakarava/kauehi', '98790', 33);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('taiaro', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('fakarava/kauehi', '98790', 34);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('niau', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('fakarava/niau', '98790', 35);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('fangatau', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('fangatau', '98765', 36);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('fakahina', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('fangatau fakahina', '98766', 37);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('akamaru', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/akamaru', '98755', 38);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('angakauitai', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/angakauitai', '98755', 39);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('aukena', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/aukena', '98755', 40);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('kamaka', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/kamaka', '98755', 41);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('makaroa', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/makaroa', '98755', 42);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('mangareva', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/mangareva', '98755', 43);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('maniui', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/maniui', '98755', 44);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('taravai', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/taravai', '98755', 45);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('maria est', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/maria est', '98792', 46);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('marutea sud', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/marutea est', '98793', 47);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('morane', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/morane', '98792', 48);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('motureivavao', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/motureivavao est', '98792', 49);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('temoe', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/temoe est', '98792', 50);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tenararo', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/tenararo', '98792', 51);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tenarunga', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/tenarunga', '98792', 52);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('vahanga', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('gambier/vahanga', '98792', 53);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('hao', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hao', '98767', 54);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('ahunui', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hao/ahunui', '98790', 55);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('hikitake amanu', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hao/amanu', '98790', 56);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('rekareka', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hao/amanu', '98790', 57);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tauere', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hao/amanu', '98790', 58);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('hereheretue', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hao/hereheretue', '98790', 59);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('anuanuraro', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hao/hereheretue', '98790', 60);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('anuanurunga', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hao/hereheretue', '98790', 61);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('nukutepipi', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hao/hereheretue', '98790', 62);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('manuhangi', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hao/manuhangi', '98790', 63);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('nengonengo', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hao/nengonengo', '98790', 64);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('paraoa', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hao/paraoa', '98790', 65);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('hikueru', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hikueru', '98768', 66);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('reitoru', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hikueru', '98790', 67);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tekokota', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hikueru', '98790', 68);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('marokau', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hikueru/marokau', '98790', 69);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('mahetika', '98790', 69);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('ravahere', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('hikueru/marokau', '98790', 70);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('kauehi', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('kauehi', '98787', 71);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('vaitepaua', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('makatea', '98790', 72);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('makemo', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('makemo', '98769', 73);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('haraiki', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('makemo', '98790', 74);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('marutea-nord', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('makemo', '98790', 75);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('katiu', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('makemo/katiu', '98790', 76);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('hiti', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('makemo/katiu', '98790', 77);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tepoto-sud', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('makemo/katiu', '98790', 78);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tuanake', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('makemo/katiu', '98790', 79);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('garumaoa raroia', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('makemo/raroia', '98790', 80);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('manihi', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('manihi', '98771', 81);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('ahe', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('manihi/ahe', '98770', 82);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('napuka', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('napuka', '98772', 83);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tepoto-nord', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('napuka/tepoto nord', '98791', 84);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tupana', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('niau', '98759', 85);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('aratika', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('nukumaru', '98764', 86);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('nukutavake', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('nukutavake', '98773', 87);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('pinaki', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('nukutavake', '98791', 88);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('akiaki', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('nukutavake/vahitahi', '98791', 89);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('vairaatea', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('nukutavake/vairaatea', '98791', 90);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('puka-puka', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('puka-puka', '98774', 91);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('pukarua', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('pukarua', '98780', 92);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('rangiroa', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('rangiroa', '98775', 93);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('rangiroa', '98776', 93);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('makatea', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('rangiroa/makatea', '98790', 94);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('mataiva', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('rangiroa/mataiva', '98777', 95);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tikehau', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('rangiroa/tikehau', '98778', 96);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('motutapu', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('raraka', '98790', 97);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('reao', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('reao', '98779', 98);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('taenga', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('taenga', '98791', 99);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('takaroa', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('takaroa', '98781', 100);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('takapoto', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('takaroa/takapoto', '98782', 101);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tikei', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('takaroa/tikei', '98790', 102);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('takume', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('takume', '98790', 103);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tatakoto', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tatakoto', '98783', 104);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tematangi', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tureia', '98791', 105);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('vanavana', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tureia', '98791', 106);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('tureia', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('tureia', '98784', 107);

INSERT INTO ILE (NAME, ARCHIPEL_ID) VALUES ('vahitahi', 4);
INSERT INTO COMMUNE (NAME,CODE,ILE_ID) VALUES ('vahitahi', '98788', 108);
